apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      nodeSelector:
        zone: us-east-1a
      containers:
        - name: vprodb
          image: vprofile/vprofiledb:v1
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          args:
            - "--ignore-db-dir=lost+found"
          volumeMounts:
            - mountPath: /var/lin/mysql
              name: vpro-db-data
          ports:
            - name: vprodb-port
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-pass
      volumes:
        - name: vpro-db-data
          awsElasticBlockStore:
            volumeID: vol-0906eb01c22a8eb12
            fsType: ext4
